components:
  schemas:
    HTTPValidationError:
      title: HTTPValidationError
      type: object
      properties:
        detail:
          title: Detail
          type: array
          items:
            $ref: "#/components/schemas/ValidationError"

    Item:
      title: Item
      type: object
      properties:
        id:
          title: Id
          type: integer
          x-faker:
            datatype.number:
              min: 50
              max: 1000
        name:
          title: Name
          type: string
          x-faker: name.firstName
        description:
          title: Description
          type: string
          x-faker: lorem.sentence
        price:
          title: Price
          type: number
          x-faker:
            datatype.number:
              min: 50
              max: 1000
        tax:
          title: Tax
          type: number
          x-faker: random.float
      required:
        - id
        - name
        - price

    ValidationError:
      title: ValidationError
      type: object
      properties:
        loc:
          title: Location
          type: array
          items:
            anyOf:
              - type: string
              - type: integer
        msg:
          title: Message
          type: string
        type:
          title: Error Type
          type: string
      required:
        - loc
        - msg
        - type

info:
  title: FastAPI
  version: 0.1.0
openapi: 3.0.0
paths:
  /items/:
    get:
      summary: Get Items
      operationId: get_items_items__get
      responses:
        "200":
          description: Successful Response
          content:
            application/json:
              schema:
                title: Response Get Items
                type: array
                items:
                  $ref: "#/components/schemas/Item"
    post:
      summary: Create Item
      operationId: create_item_items__post
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Item"
      responses:
        "200":
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Item"
        "422":
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HTTPValidationError"

  /items/{item_id}:
    get:
      summary: Get Item
      operationId: get_item_items__item_id__get
      parameters:
        - name: item_id
          in: path
          required: true
          schema:
            title: Item Id
            type: integer
      responses:
        "200":
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Item"
        "422":
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HTTPValidationError"

    put:
      summary: Update Item
      operationId: update_item_items__item_id__put
      parameters:
        - name: item_id
          in: path
          required: true
          schema:
            title: Item Id
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Item"
      responses:
        "200":
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Item"
        "422":
          description: Validation Error
